version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap
          command: yarn run bootstrap
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Unit Test
          command: yarn run test:unit --maxConcurrency=1 # CircleCI runs out of mem
      - run:
          name: Integration Test
          command: yarn run test:integration
      # - setup_remote_docker
      # - run:
      #     name: Integration Test
      #     command: |
      #       docker run --name rabbit -d -p 8080:15672 -p 5672:5672 rabbitmq:3-management
      #       docker create -v /repo --name repo alpine:3.4 /bin/true
      #       docker cp . repo:/repo
      #       docker run -it --volumes-from repo --workdir /repo/bus node:8.15.0 yarn test:integration
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    <<: *defaults
    docker:
      - image: circleci/node:16
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish
          command: npx lerna publish from-package --yes

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
